project_name: "Llandeilo Through Time"
default_status: "Idea"
statuses: ["Idea", "Agreed", "Researching", "Research verified", "Building", "Review", "Done"]
types: ["content", "look", "research", "code"]
labels: []
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "nvim"
auto_open_browser: false
default_port: 5052
remote_operations: false
auto_commit: false
filesystem_only: false
zero_padded_ids: 3
bypass_git_hooks: false
check_active_branches: false
active_branch_days: 30
task_prefix: "t"
backlog_directory: "docs/todos"
